### PR TITLE
Feat: Trade Advancements

### PR DESCRIPTION
**Pull request by EngineerSmith**
* Added Trade Advancement for picking up an incomplete trade - to hint to the player to trade
* Added auto-generating advancements (hidden) to be used for backwards compatibility

### CODE REVIEW

**Review by EngineerSmith — COMMENTED** [review]
I've read through the code and nothing pops out at me. It works in both old and new worlds and doesn't cause any errors

**Comment by JonerCrack1** [comment]
Test 123

**Comment by JonerCrack1** [comment]
way to many updates...
image

**Comment by Yarden-zamir** [comment]
No such thing as too many updates @JonerCrack1

**Pull request merged**
