### PR TITLE
mods: change ptdye-plus side to client

### PR DESCRIPTION
**Pull request by jasperalani**
https://discord.com/channels/890222432605057044/1193208804251275285

### CODE REVIEW

**Comment by Yarden-zamir** [comment]
That's not gonna be enough I think, we don't read the manifest when creating the server, that would help only people using mrpack isntall

**Comment by jasperalani** [comment]
ok i found out how to make my mod only load on client and did a silent update to modrinth and curseforge so 1.2.4 now wont load on server at all.
this should be good to go then.

**Comment by Yarden-zamir** [comment]
Didn't know silent updates were legal, feels like the shouldn't be. I don't want my dependencies to change under me

**Comment by jasperalani** [comment]
yeah i just got tired of manually updating across github, modrinth and curseforge
ill make it visible

**Comment by jasperalani** [comment]
made a new release: 1.3.0
https://modrinth.com/mod/ptdye-plus/version/1.3.0
https://legacy.curseforge.com/minecraft/mc-mods/ptdye-plus/files/5014880

**Comment by Yarden-zamir** [comment]
Try to update them yourself in a pr with packwiz maybe it will reduce the friciton a bit. Also it seems that the bot treats prs as issues but only parcially

**Comment by Yarden-zamir** [comment]
We can make automated prs when updates are avilable

**Comment by Yarden-zamir** [comment]
Ah I think the bot's issue is with labeling the pr, once it's labeled it can forward things fine

**Comment by Yarden-zamir** [comment]
Good, but also do the same in the curseforge folder

**Pull request merged**
